name: manual workflow

on:
  workflow_dispatch:
   inputs:
     name:
      description: 'Name'
      type: string
      default: 'test'
    age:
      description: 'Age'
      type: number
      required: true
      
      
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: greetings
        run: echo "${{ input.name }}"

      - name: Age
        run: echo "${{ inputs.age }}"
